###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/123e4567-e89b-12d3-a456-426614174000

###
GET http://localhost:3000/users/123e4567-e89b-12d3-a456-426614194000

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Javier Pulido",
  "email": "jaasdlssas@gmail.com",
  "password": "12345678",
  "phone": "123343789",
  "role": "admin",
  "address":"MICASA",
  "dni": "02322329B"
}



###
POST http://localhost:3000/users
Content-Type: application/json

{
  "id" : "345e4567-e89b-12d3-a456-426614174422",  
  "name": "Javier Pulido",
  "email": "jaaadsfsl@gmail.com",
  "password": "12345678",
  "phone": "123423009",
  "role": "user",
  "address":"MICASA",
  "dni": "02342422B"
}

###
PATCH http://localhost:3000/users/234e4567-e89b-12d3-a456-426614174111
Content-Type: application/json

{
  "name": "Nicolas",
  "dni": "04325549B",
  "role": "user"
}

###
DELETE http://localhost:3000/users/123e4567-e89b-12d3-a456-426614174000


###
GET http://localhost:3000/reservations

###
GET http://localhost:3000/reservations/2

###
GET http://localhost:3000/reservations/SELECT * FROM reservations	

### 
POST http://localhost:3000/reservations
Content-Type: application/json

{
  "vehicle_id":2,
  "customer_id":"234e4567-e89b-12d3-a456-426614174111",
  "start_date":"2023-05-10 09:00:00",
  "end_date":"2023-05-12 09:00:00",
  "total_price":50.00
}

###
POST http://localhost:3000/reservations
Content-Type: application/json

{
  "vehicle_id":2,
  "customer_id":"234e4567-e89b-12d3-a456-426614174111",
  "start_date":"2023-05-15 09:00:00",
  "end_date":"2023-05-17 09:00:00",
  "total_price":50.00

}

###
PATCH http://localhost:3000/reservations/4
Content-Type: application/json

{
  "status": "cancelled",
  "total_price": 60.50
}

###
PATCH http://localhost:3000/reservations/4
Content-Type: application/json

{
  "id" : 4,
  "status": "cancelled",
  "total_price": 60.50
}

###
GET http://localhost:3000/reservations/4

###
DELETE http://localhost:3000/reservations/4

###
GET http://localhost:3000/reservations/vehicle/2

###
GET http://localhost:3000/reservations/customer/234e4567-e89b-12d3-a456-426614174111