DELIMITER //

CREATE FUNCTION BIN_TO_UUID(b BINARY(16)) RETURNS CHAR(36)
DETERMINISTIC
BEGIN
  RETURN LOWER(CONCAT(
    SUBSTR(HEX(b), 1, 8), '-',
    SUBSTR(HEX(b), 9, 4), '-',
    SUBSTR(HEX(b), 13, 4), '-',
    SUBSTR(HEX(b), 17, 4), '-',
    SUBSTR(HEX(b), 21)
  ));
END //

DELIMITER ;

DELIMITER //

CREATE FUNCTION UUID_TO_BIN(uuid CHAR(36)) RETURNS BINARY(16)
DETERMINISTIC
BEGIN
  RETURN UNHEX(CONCAT(
    SUBSTRING(uuid, 1, 8),
    SUBSTRING(uuid, 10, 4),
    SUBSTRING(uuid, 15, 4),
    SUBSTRING(uuid, 20, 4),
    SUBSTRING(uuid, 25)
  ));
END //

DELIMITER ;
